<a href="https://colab.research.google.com/github/heerboi/AI-from-scratch/blob/main/ROPE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [14]:
x = torch.arange(20)
x.view(5, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

assuming sequence length 5, with each token having 4 dims

In [15]:
num = torch.arange(0, 4, 2).float()
num

tensor([0., 2.])

In [16]:
thetas = 1.0/10000**(num/4)
thetas

tensor([1.0000, 0.0100])

In [17]:
m = torch.arange(5)
m

tensor([0, 1, 2, 3, 4])

In [18]:
#mthetas
# seq_len x seq_len/2
freqs = torch.outer(m, thetas).float()
freqs

tensor([[0.0000, 0.0000],
        [1.0000, 0.0100],
        [2.0000, 0.0200],
        [3.0000, 0.0300],
        [4.0000, 0.0400]])

In [20]:
# polar uses abs and angle arg as: abs*cos(angle) + abs*sin(angle)*i
freqs_complex = torch.polar(torch.ones_like(freqs), freqs)
freqs_complex

tensor([[ 1.0000+0.0000j,  1.0000+0.0000j],
        [ 0.5403+0.8415j,  0.9999+0.0100j],
        [-0.4161+0.9093j,  0.9998+0.0200j],
        [-0.9900+0.1411j,  0.9996+0.0300j],
        [-0.6536-0.7568j,  0.9992+0.0400j]])

In [25]:
x = x.view(5, 4)
# break into pairs of two = (5, 4) -> (5, 2, 2)
x_broken_down = x.float().reshape(*x.shape[:-1], -1, 2)

In [28]:
x_broken_down_complex = torch.view_as_complex(x_broken_down)

In [29]:
x_broken_down_complex

tensor([[ 0.+1.j,  2.+3.j],
        [ 4.+5.j,  6.+7.j],
        [ 8.+9.j, 10.+11.j],
        [12.+13.j, 14.+15.j],
        [16.+17.j, 18.+19.j]])

In [30]:
rot_x_complex = x_broken_down_complex * freqs_complex
rot_x_complex

tensor([[  0.0000+1.0000j,   2.0000+3.0000j],
        [ -2.0461+6.0674j,   5.9297+7.0596j],
        [-11.5129+3.5291j,   9.7780+11.1978j],
        [-13.7145-11.1765j,  13.5438+15.4132j],
        [  2.4073-23.2208j,  17.2258+19.7046j]])

In [35]:
rot_x = torch.view_as_real(rot_x_complex).reshape(*x.shape[:-1], -1)
rot_x

tensor([[  0.0000,   1.0000,   2.0000,   3.0000],
        [ -2.0461,   6.0674,   5.9297,   7.0596],
        [-11.5129,   3.5291,   9.7780,  11.1978],
        [-13.7145, -11.1765,  13.5438,  15.4132],
        [  2.4073, -23.2208,  17.2258,  19.7046]])

In [36]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])